### PR TITLE
follow symlink

### PR DESCRIPTION
**Pull request by jakech**

### CODE REVIEW

**Comment by jakech** [comment]
broke your test, fixing

**Comment by jakech** [comment]
now it will follow symlink to delete files, but won't delete the actual directory when only the symlink is target for deletion.

**Comment by louisbuchbinder** [comment]
I like where this is going. Definitely the tests should be fixed in the way you did to test the local script instead of the global one. Send a separate pull for that update. So I can include you as a team member on my linkedin.

The way this is now. When the symlink is used as the target it will delete the original file, but when the original file is the target the symlink will not be deleted. Also after the original file is deleted if you try to delete the symlink it will throw an error because the target cannot be found.

I am not sure that this is the desired functionality. For example I may want to delete the symlink but not the original file. However, in the case when I want to delete the original file I do want to delete the symlinks as well. This would be the reverse behavior of readlink.

The answer I found for reverse readlink says this reverse functionality is not simple and they basically suggest crawling the entire fs (that seems a bit crazy to me). http://stackoverflow.com/questions/4532241/linux-find-all-symlinks-of-a-given-original-file-reverse-readlink


Let me know what you think. Also check out these examples to show what I mean.

```
# 1.
touch temp.txt; ln -s temp.txt temp-s.txt
./bin/safe-delete temp-s.txt
# this will delete the temp-s.txt and the temp.txt (but what if I only meant to delete the symlink?)


# 2.
touch temp.txt; ln -s temp.txt temp-s.txt
./bin/safe-delete temp.txt
# this will delete the temp.txt and not the temp-s.text (in this case I probably want to delete the temp-s.txt as well)
# now if I try to delete the temp-s.txt it will throw an error
./bin/safe-delete temp-s.txt
# Error: temp-s.txt was not found.

```

Revision: the error is actually occurring because I am testing if the file or directory exists using `if [[ -f $var ]] || [[ -d $var ]]` but this is false for broken symlinks... Interesting. I can change it to `if test "$(ls $var)"` and it will not throw the error.

**Comment by louisbuchbinder** [comment]
Revision 2: it looks like it is better to use `if [ -e <filename> ]` when testing for existence

**Comment by louisbuchbinder** [comment]
I'm closing this one. Lets talk later

**Comment by jakech** [comment]
Hmmmm... this is tricky. 
Following symlink was intended to follow directory

Example:

``` bash
mkdir abcd
touch abcd/temp.txt
ln -s abcd portal
```

They you would expect `del ./portal/temp.txt` to actually delete the file for you? no?

Maybe we could have it as an option. Let me know what you think.

**Pull request closed without merging**
